name: build mac app

on: [push, pull_request]

jobs:
  build: BigGuy573/nat/keyrace/.github/workflows/build_app.yml
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - name: Select Xcode 12.4
        run: sudo xcode-select -switch /Applications/Xcode_12.4.app
      - name: Build project
        run: make keyrace-mac
      - name: Save .zip as artifact
        uses: actions/upload-artifact@v1
        with:
          name: keyrace-mac.app
          path: ./build/mac
- name: First interaction
  uses: actions/first-interaction@v1.1.0
  with: BigGuy573/nat/keyrace/.github/workflows/build_app.yml
    # Token for the repository. Can be passed in using {{ secrets.GITHUB_TOKEN }}
    repo-token: 
    # Comment to post on an individual's first issue
    issue-message: # optional
    # Comment to post on an individual's first pull request
    pr-message: # optional
